services:
  - type: web
    name: vocalist-screening-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python run_bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: GOOGLE_DRIVE_FOLDER_ID
        sync: false
      - key: GOOGLE_SHEET_ID
        sync: false
      - key: GOOGLE_SHEET_RANGE
        value: A:G
      - key: DATABASE_PATH
        value: ./data/vocalist_screening.db
      - key: REVIEWER_TELEGRAM_CHAT_ID
        sync: false
      - key: REVIEWER_EMAIL
        sync: false
      - key: GOOGLE_CREDENTIALS_FILE
        value: ./credentials.json
    disk:
      name: data
      mountPath: /opt/render/project/data
      sizeGB: 1
